[package]
name = "kalosm-language-model"
version = "0.3.3"
edition = "2021"
description = "A common interface for language models/transformers "
license = "MIT/Apache-2.0"
repository = "https://github.com/floneum/floneum"
authors = ["Evan Almloff"]
keywords = ["ai", "llm", "llama", "mistral", "nlp"]

[dependencies]
futures-util = "0.3.28"
futures-channel = "0.3.31"
llm-samplers = { workspace = true }
log = "0.4.17"
rand = "0.8.5"
serde = { version = "1.0.163", features = ["derive"], optional = true }
once_cell = "1.18.0"
tracing = "0.1.37"
candle-core.workspace = true
kalosm-sample = { workspace = true }
kalosm-common.workspace = true
thiserror.workspace = true
lru = { version = "0.12.3", optional = true }
reqwest = { version = "0.12.12", features = ["json"], optional = true }
serde_json = { version = "1.0.134", optional = true }
reqwest-eventsource = { version = "0.6.0", optional = true }
anyhow = { workspace = true }
async-lock = "3.4.0"
dynosaur = "0.1.2"

[dev-dependencies]
tokio = { version = "1.28.1", features = ["full"] }
kalosm = { workspace = true, features = ["language"] }
kalosm-learning = { workspace = true }
pretty_assertions = "1.4.1"
postcard = { version = "1.0.8", features = ["use-std"] }

[features]
default = ["cache"]
anthropic = ["dep:reqwest", "dep:serde_json", "dep:reqwest-eventsource"]
openai = ["dep:reqwest", "dep:serde_json", "dep:reqwest-eventsource"]
remote = ["anthropic", "openai"]
serde = ["dep:serde"]
cache = ["serde", "dep:lru"]

[package.metadata.docs.rs]
# Features to pass to Cargo (default: [])
features = ["remote"]
